[package]
name = "pallet-gear-program"
version = "2.0.0"
authors = ['Gear Technologies']
edition = '2018'
license = "GPL-3.0"
homepage = "https://gear-tech.io"
repository = "https://github.com/gear-tech/gear"
description = "Gear pallet to work with programs"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.1.2", default-features = false, features = ["derive"] }
scale-info = { version = "2.1.1", default-features = false, features = ["derive"] }
primitive-types = { version = "0.11.1", default-features = false, features = ["scale-info"] }
log = { version = "0.4.17", default-features = false }
wasm-instrument = { version = "0.2", default-features = false }

# Internal deps
common = { package = "gear-common", path = "../../common", default-features = false }
gear-core = { path = "../../core", default-features = false }

# Substrate deps
frame-benchmarking = { git = "https://github.com/gear-tech/substrate", default-features = false, optional = true, branch = "polkagear3000-v0.9.26" }
frame-support = { git = "https://github.com/gear-tech/substrate", default-features = false, branch = "polkagear3000-v0.9.26" }
frame-system = { git = "https://github.com/gear-tech/substrate", default-features = false, branch = "polkagear3000-v0.9.26" }
sp-core = { git = "https://github.com/gear-tech/substrate", default-features = false, branch = "polkagear3000-v0.9.26" }
sp-std = { git = "https://github.com/gear-tech/substrate", default-features = false, branch = "polkagear3000-v0.9.26" }
sp-io = { git = "https://github.com/gear-tech/substrate", default-features = false, branch = "polkagear3000-v0.9.26" }
sp-runtime = { git = "https://github.com/gear-tech/substrate", default-features = false, branch = "polkagear3000-v0.9.26" }
pallet-balances = { git = "https://github.com/gear-tech/substrate", default-features = false, branch = "polkagear3000-v0.9.26" }

[dev-dependencies]
hex-literal = "0.3.3"
env_logger = "0.9"
pallet-gear-gas = { path = "../gas", default-features = false }
pallet-gear-messenger = { path = "../gear-messenger", default-features = false }

[features]
default = ['std']
std = [
	"log/std",
	"codec/std",
	"common/std",
	"frame-support/std",
	"frame-system/std",
	"scale-info/std",
	"sp-io/std",
	"sp-std/std",
	"sp-core/std",
	"sp-runtime/std",
	"primitive-types/std",
	"pallet-balances/std",
	"pallet-gear-messenger/std",
	"pallet-gear-gas/std",
]
runtime-benchmarks = [
	"frame-benchmarking",
	"frame-system/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"common/runtime-benchmarks"
]
