[package]
name = "regression-analysis"
version = "0.1.0"
authors = ["Gear Technologies"]
edition = "2018"
license = "GPL-3.0"

[dependencies]
clap = { version = "3.2", features = ["derive"] }
quick-xml = { version = "0.23", features = [ "serialize" ] }
tabled = "0.8.0"
junit-common = { path = "../junit-common" }
serde = { version = "1.0.138", features = ["derive"] }
serde_json = "1.0.82"
thousands = "0.2.0"
once_cell = "1.13.0"

gear-runtime = { path = "../../runtime" }
pallet-authorship = { version = "4.0.0-dev", default-features = false, git = "https://github.com/gear-tech/substrate.git", branch = "gear-stable" }
pallet-timestamp = { version = "4.0.0-dev", default-features = false, git = "https://github.com/gear-tech/substrate.git", branch = "gear-stable" }
pallet-balances = { version = "4.0.0-dev", default-features = false, git = "https://github.com/gear-tech/substrate.git", branch = "gear-stable" }
pallet-gear-messenger = { version = "1.0.0", default-features = false, path = "../../pallets/gear-messenger" }
pallet-gear-gas = { path = "../../pallets/gas", default-features = false }
pallet-gear-program = { path = "../../pallets/gear-program" }
pallet-gear-scheduler = { version = "1.0.0", default-features = false, path = "../../pallets/gear-scheduler" }
pallet-gear = { path = "../../pallets/gear" }
frame-system = { version = "4.0.0-dev", git = "https://github.com/gear-tech/substrate.git", branch = "gear-stable" }
frame-support = { version = "4.0.0-dev", git = "https://github.com/gear-tech/substrate.git", branch = "gear-stable" }
codec = { package = "parity-scale-codec", version = "3.1.2", features = ["derive"], default-features = false }
scale-info = { version = "2.1.1", default-features = false, features = ["derive"] }
