[workspace]
resolver = "2"

default-members = ["node"]

members = [
    "common",
    "common/codegen",
    "core",
    "core-backend/common",
    "core-backend/sandbox",
    "core-backend/wasmi",
    "core-processor",
    "core-errors",
    "examples/binaries/*",
    "galloc",
    "gcore",
    "gear-test",
    "gstd",
    "gtest",
    "node",
    "pallets/*",
    "runtime/gear",
    "runtime/parachain-gear",
    "runtime/vara",
    "utils/gear-runtime-test-cli",
    "utils/regression-analysis",
    "utils/junit-common",
    "utils/wasm-proc",
    "utils/wasm-builder",
    "utils/economic-checks",
    "utils/economic-checks/fuzz",
]

[profile.release]
panic = "unwind"

[profile.release.package.gcore]
opt-level = "s"

[profile.release.package.gstd]
opt-level = "s"

[profile.release.package.gear-test]
opt-level = "s"

[profile.release.package.galloc]
opt-level = "s"

[profile.release.package.gtest]
opt-level = "s"

[profile.production]
inherits = "release"

# Sacrifice compile speed for execution speed by using optimization flags:

# https://doc.rust-lang.org/rustc/linker-plugin-lto.html
lto = "fat"
# https://doc.rust-lang.org/rustc/codegen-options/index.html#codegen-units
codegen-units = 1

[patch."https://github.com/paritytech/substrate"]
frame-benchmarking = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
frame-benchmarking-cli = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
frame-executive = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
frame-support = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
frame-system = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
frame-system-benchmarking = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
frame-system-rpc-runtime-api = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
frame-try-runtime = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
pallet-aura = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
pallet-authorship = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
pallet-balances = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
pallet-session = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
pallet-sudo = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
pallet-timestamp = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
pallet-transaction-payment = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
pallet-transaction-payment-rpc = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
pallet-transaction-payment-rpc-runtime-api = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
pallet-utility = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
sc-basic-authorship = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
sc-chain-spec = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
sc-cli = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
sc-client-api = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
sc-consensus = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
sc-executor = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
sc-keystore = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
sc-network = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
sc-rpc = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
sc-rpc-api = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
sc-service = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
sc-sysinfo = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
sc-telemetry = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
sc-tracing = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
sc-transaction-pool = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
sc-transaction-pool-api = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
sp-api = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
sp-block-builder = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
sp-blockchain = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
sp-consensus = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
sp-consensus-aura = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
sp-core = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
sp-externalities = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
sp-inherents = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
sp-keystore = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
sp-io = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
sp-offchain = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
sp-rpc = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
sp-runtime = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
sp-runtime-interface = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
sp-sandbox = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
sp-session = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
sp-std = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
sp-timestamp = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
sp-transaction-pool = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
sp-version = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
substrate-frame-rpc-system = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
substrate-prometheus-endpoint = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
substrate-wasm-builder = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
try-runtime-cli = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }

sp-consensus-slots = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
sc-executor-common = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
sc-executor-wasmtime = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
sp-staking = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
sp-consensus-vrf = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
sp-npos-elections = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
sp-keyring = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
sp-authority-discovery = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
beefy-primitives = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
sp-mmr-primitives = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
sp-finality-grandpa = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
beefy-merkle-tree = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
sp-authorship = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
sp-consensus-babe = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
pallet-authority-discovery = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
pallet-mmr = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
pallet-beefy = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
frame-election-provider-support = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
pallet-staking = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
pallet-election-provider-multi-phase = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
pallet-bags-list = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
pallet-im-online = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
sp-application-crypto = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
sp-state-machine = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
sp-trie = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
pallet-babe = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
pallet-grandpa = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
sc-consensus-babe = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
sc-consensus-epochs = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
sc-consensus-slots = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
sc-client-db = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
sc-consensus-uncles = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
sc-state-db = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
sc-block-builder = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
pallet-mmr-rpc = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
pallet-vesting = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
sc-finality-grandpa = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
sc-offchain = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
sc-network-gossip = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
sc-authority-discovery = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
pallet-identity = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
pallet-democracy = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
pallet-preimage = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
pallet-scheduler = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
pallet-collective = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
pallet-indices = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
pallet-multisig = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
pallet-elections-phragmen = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
pallet-proxy = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
pallet-offences = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
pallet-treasury = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
pallet-membership = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
pallet-child-bounties = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
pallet-tips = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
pallet-bounties = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
substrate-state-trie-migration-rpc = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
pallet-beefy-mmr = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
sc-sync-state-rpc = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
sc-finality-grandpa-rpc = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
beefy-gadget = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
sc-consensus-babe-rpc = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
beefy-gadget-rpc = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
sp-arithmetic = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
sp-debug-derive = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
pallet-staking-reward-curve = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
sp-tracing = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
sp-wasm-interface = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
sp-storage = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
sp-maybe-compressed-blob = { git = "https://github.com/gear-tech/substrate", branch = "polkagear3000-v0.9.26" }
