[package]
name = "gear-node-primitives"
version = "1.0.0"
authors = ["Gear Technologies"]
description = "Gear Node primitives"
edition = "2018"
license = "GPL-3.0"
homepage = "https://gear-tech.io"
repository = "https://github.com/gear-tech/gear"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
sp-core = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.26" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.26" }

[features]
default = ["std"]
std = [
	"sp-core/std",
	"sp-runtime/std",
]
