[package]
name = "pallet-gear-rpc"
version = "2.0.0"
authors = ['Gear Technologies']
edition = '2018'
license = "GPL-3.0"
homepage = "https://gear-tech.io"
repository = "https://github.com/gear-tech/gear"

[dependencies]
jsonrpsee = { version = "0.14.0", features = ["server", "macros"] }

# Substrate packages
sp-api = { git = "https://github.com/gear-tech/substrate", default-features = false, branch = "polkagear3000-v0.9.26" }
sp-blockchain = { git = "https://github.com/gear-tech/substrate", default-features = false, branch = "polkagear3000-v0.9.26" }
sp-core = { git = "https://github.com/gear-tech/substrate", default-features = false, branch = "polkagear3000-v0.9.26" }
sp-rpc = { git = "https://github.com/gear-tech/substrate", default-features = false, branch = "polkagear3000-v0.9.26" }
sp-runtime = { git = "https://github.com/gear-tech/substrate", default-features = false, branch = "polkagear3000-v0.9.26" }

# Local packages
gear-core = { path = "../../../core" }
gear-common = { path = "../../../common" }
pallet-gear-rpc-runtime-api = { version = "2.0.0", path = "./runtime-api" }
