[package]
name = "pallet-gear-rpc-runtime-api"
version = "2.0.0"
authors = ['Gear Technologies']
edition = '2018'
license = "GPL-3.0"
homepage = "https://gear-tech.io"
repository = "https://github.com/gear-tech/gear"

[dependencies]
sp-api = { git = "https://github.com/gear-tech/substrate", default-features = false, branch = "polkagear3000-v0.9.26" }
sp-core = { git = "https://github.com/gear-tech/substrate", default-features = false, branch = "polkagear3000-v0.9.26" }
sp-std = { git = "https://github.com/gear-tech/substrate", default-features = false, branch = "polkagear3000-v0.9.26" }
pallet-gear = { version = "2.0.0", default-features = false, path = "../../../gear" }

[features]
default = ["std"]
std = [
    "pallet-gear/std",
	"sp-api/std",
	"sp-core/std",
]
