[package]
name = "gear-runtime-test-cli"
version = "0.1.0"
authors = ["Gear Technologies"]
edition = "2018"
license = "GPL-3.0"

[dependencies]
anyhow = "1.0.59"
codec = { package = "parity-scale-codec", version = "3.1.2", default-features = false, features = ["derive"] }
colored = "2.0.0"
clap = { version = "3.2", features = ["derive"] }
log = { version = "0.4.17", default-features = false }
serde_json = "1.0.82"
quick-xml = { version = "0.23", features = [ "serialize" ] }
rayon = "1.5"

# Substrate deps
frame-support = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.26" }
frame-system = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.26" }
sc-cli = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.26" }
sp-consensus-aura = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.26" }
sp-core = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.26" }
sp-io = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.26" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.26" }
sc-service = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.26" }
pallet-balances = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.26" }

# Internal deps
gear-common = { path = "../../common" }
gear-core = { path = "../../core" }
gear-runtime = { path = "../../runtime", features = ["debug-mode"] }
gear-test = { path = "../../gear-test" }
pallet-gear = { path = "../../pallets/gear" }
pallet-gear-gas = { path = "../../pallets/gas" }
pallet-gear-debug = { path = "../../pallets/gear-debug" }
gear-core-processor = { path = "../../core-processor" }
junit-common = { path = "../junit-common" }
