[package]
name = "economic-checks"
version = "0.1.0"
authors = ["Gear Technologies"]
edition = "2018"
license = "GPL-3.0"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.1.2", features = ["derive"] }
log = { version = "0.4.17" }
parity-wasm = { version = "0.45.0" }
parking_lot = "0.12.0"
primitive-types = { version = "0.11.1", features = ["scale-info"] }
rand = { version = "0.8.5", features = ["std_rng"] }
serde = "1"
env_logger = "0.9"
hex = "0.4.3"
arbitrary = { version = "1" }
wasm-mutate = "0.2.7"
wasmparser = "0.89.1"

# Internal deps
common = { package = "gear-common", path = "../../common" }
runtime-primitives = { package = "gear-runtime-primitives", version = "0.1.0", default-features = false, path = "../../runtime/primitives" }
gear-core = { path = "../../core" }
gear-runtime = { path = "../../runtime/gear", optional = true }
vara-runtime = { path = "../../runtime/vara", optional = true }
pallet-gear-gas = { path = "../../pallets/gas" }
pallet-gear = { path = "../../pallets/gear" }
demo-contract-template = { path = "../../examples/binaries/contract-template" }
demo-mul-by-const = { path = "../../examples/binaries/mul-by-const" }
demo-ncompose = { path = "../../examples/binaries/ncompose" }

# Substrate deps
frame-support = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.26" }
frame-system = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.26" }
sc-cli = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.26" }
sp-consensus-aura = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.26", optional = true }
sp-consensus-babe = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.26", optional = true }
sp-consensus-slots = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.26" }
sp-core = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.26" }
sp-finality-grandpa = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.26" }
sp-io = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.26" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.26" }
sc-service = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.26" }
sp-std = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.26" }
pallet-aura = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.26" }
pallet-authorship = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.26" }
pallet-balances = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.26" }

[dev-dependencies]
wat = "1.0"
wasmprinter = "0.2.39"
demo-compose = { path = "../../examples/binaries/compose" }

[features]
default = ["gear-native", "lazy-pages"]
lazy-pages = [
    "gear-runtime?/lazy-pages",
    "vara-runtime?/lazy-pages",
    "pallet-gear/lazy-pages",
]
debug-wasm-mutate = []
gear-native = ["gear-runtime", "sp-consensus-aura", "authoring-aura"]
vara-native = ["vara-runtime", "sp-consensus-babe"]
authoring-aura = []
